/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */
declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


import {
  LottieAnimation as LottieAnimation
} from './components/lottie-animation/lottie-animation';

declare global {
  interface HTMLLottieAnimationElement extends LottieAnimation, HTMLStencilElement {
  }
  var HTMLLottieAnimationElement: {
    prototype: HTMLLottieAnimationElement;
    new (): HTMLLottieAnimationElement;
  };
  interface HTMLElementTagNameMap {
    'lottie-animation': HTMLLottieAnimationElement;
  }
  interface ElementTagNameMap {
    'lottie-animation': HTMLLottieAnimationElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'lottie-animation': JSXElements.LottieAnimationAttributes;
    }
  }
  namespace JSXElements {
    export interface LottieAnimationAttributes extends HTMLAttributes {
      /**
       * input the lottie data directly to the component
       */
      'animationData'?: string;
      'autoplay'?: boolean;
      'controls'?: boolean;
      'count'?: number;
      'direction'?: number;
      'loop'?: boolean;
      'renderer'?: string;
      'speed'?: number;
      /**
       * Get the animation via src attribute
       */
      'src'?: string;
      
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
